version: "3.8"

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: ./client
      target: development
    volumes:
      - ./client/src:/app/src
      - /client/node_modules
    ports:
      - 3000:3000
  server:
    container_name: server-dev
    image: server-dev
    build:
      context: ./server
      target: development
    volumes:
      - ./server/src:/server/src
      - /server/node_modules
    ports:
      - 8000:8000
