version: "3.8"

services:
  app:
    container_name: app-prod
    image: app-prod
    build:
      context: ./client
      target: production
      dockerfile: Dockerfile.production
  server:
    container_name: server-prod
    image: server-prod
    build:
      context: ./server
      target: production
      dockerfile: Dockerfile.production
    ports:
      - 8081:8081
